spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-52-71-69-66.compute-1.amazonaws.com:5432/d2knfsqsomnm0e
    username: ykgfxibvkkhhlm
    password: af59ac605fb1ba59ce96278e7988b67829959bc2797d59f02e88895bd9ccc3bb



