CREATE TABLE public.tb_customer (
	id int generated by default as identity,
	email_customer varchar(255) ,
	name_customer varchar(255) ,
	CONSTRAINT tb_customer_pkey PRIMARY KEY (id),
	CONSTRAINT tb_customer_un UNIQUE (email_customer)
);
