CREATE TABLE public.tb_book (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name_book varchar(255) NULL,
	price numeric(10, 2) NULL,
	status varchar(255) NULL,
	customer_id int4 NULL,
	CONSTRAINT tb_book_pkey PRIMARY KEY (id),
	CONSTRAINT tb_book_fkey FOREIGN KEY (customer_id) REFERENCES public.tb_customer(id)
);



