CREATE TABLE public.tb_book (
	id_book int generated by default as identity,
	name_book varchar(255) ,
	price numeric(10, 2) ,
	status varchar(255) ,
	customer_id int ,
	CONSTRAINT tb_book_pkey PRIMARY KEY (id_book),
	CONSTRAINT tb_book_fkey FOREIGN KEY (customer_id) REFERENCES public.tb_customer(id)
);
